# Generated by Django 6.0.3 on 2026-04-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
