# Generated by Django 6.0.3 on 2026-04-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
