# Generated by Django 6.0.3 on 2026-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
